# theme = "fotsies_github_dark_dimmed"
# theme = "fotsies_darcula"
# theme = "fotsies_gruvbox"
# theme = "fotsies_rose_pine_moon"
# theme = "fotsies_autumn"
# theme = "fotsies_sonokai"
theme = "fotsies_monokai_pro"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
rulers = [100]
shell = ["pwsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
C-c = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.insert]
# Use an easier escape sequence.
C-c = "normal_mode"

[keys.select]
# Use an easier escape sequence.
C-c = "normal_mode"
