# theme = "fotsies_github_dark_dimmed"
# theme = "fotsies_darcula"
# theme = "fotsies_gruvbox"
# theme = "fotsies_rose_pine_moon"
# theme = "fotsies_autumn"
# theme = "fotsies_sonokai"
theme = "fotsies_monokai_pro"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
rulers = [100]
shell = ["pwsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
# C-c = "no_op"
C-c = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.insert]
# Disable arrow keys in insert mode.
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
# Map various shortcuts to make moving easier while in insert mode.
A-j = "move_line_up"
A-k = "move_line_down"
A-h = "move_char_left"
A-l = "move_char_right"
A-H = "goto_line_start"
A-S = "goto_first_nonwhitespace"
A-L = "goto_line_end_newline"
A-w = "move_next_word_start"
# Use an easier escape sequence.
C-c = "normal_mode"

[keys.select]
# Use an easier escape sequence.
C-c = "normal_mode"
